### ISSUE TITLE
线程执行中可能存在的一个错误

### ISSUE THREAD

**Issue by fjfzzl** [shidenggui/easytrader#100]
你好！
我昨天在我的windows机器上的anaconda python命令行环境下，运行了 user = easytrader.use('yjb') 和 user.prepare('yjb.json') ，然后隔一段时间执行一次 user.balance，刚开始每次都能返回正确结果，后来间隔时间拉大，早上起来运行了  user.balance就出现错误了，马上接着运行一次 user.balance，又返回正确结果。今天下午再运行一次  user.balance的时候，又出现同样的错误，截图出来了，根据提示，线程只能被started 一次，好像是作者的命令有逻辑错误，请作者检查一下。可能是在检查出掉线后，试图再次登陆，然后又调用了一次 self.heart_thread.start()，然后导致的出错。

![easytrader-error](https://cloud.githubusercontent.com/assets/19483013/17995882/e7062e26-6b97-11e6-87e3-27918f7fa1fb.jpg)

**Comment by shidenggui** [comment]
已经修复了
