### ISSUE TITLE
现在这个时刻，我无法通过easytrader登录到我的佣金宝账户，可是官方网页却可以正常登陆

### ISSUE THREAD

**Issue by fjfzzl** [shidenggui/easytrader#104]
现在这个时刻，我无法通过easytrader登录到我的佣金宝账户（我没改动过代码，昨天还可以好好运行），可是官方网页却可以正常登陆。
user.prepare('yjb.json')
提示的错误信息是：
![01](https://cloud.githubusercontent.com/assets/19483013/18032730/e55c8222-6d41-11e6-8239-1a019cba2a53.JPG)

这个是怎么回事呢？

**Comment by yerrick** [comment]
我官方网页也登入不了，就是不能登吧现在。

**Comment by fjfzzl** [comment]
奇怪了！那台不能通过easytrader登录的机器，也无法通过正常IE登录，但是我在别的机器上却可以IE登陆成功！难道佣金宝侦测出我们用软件登陆，将我们的IP地址屏蔽了吗？

**Comment by yerrick** [comment]
估计只是不同机房不同集群在调试之类的吧，并不知道。屏蔽我觉得应该不会的。

**Comment by fjfzzl** [comment]
我想很大可能是被屏蔽了！因为在别的不同段的IP都可以正常登陆！

**Comment by shidenggui** [comment]
周六周日维护有时候不能正常登录

**Comment by fjfzzl** [comment]
你说的周六周日维护有时候不能正常登录，可是我在我家的电脑上却可以IE正常登录，在远程服务器上不能登录，怎么回事？还有就是今天上午远程服务器还不行，刚才在交易的时候我又在服务器上登陆成功了，这是怎么回事？

**Comment by shidenggui** [comment]
网络问题
