### ISSUE TITLE
华泰ETF交易还是有问题

### ISSUE THREAD

**Issue by lyghid** [shidenggui/easytrader#106]
user.buy(sh510050, price=2.100, amount=100)
Traceback (most recent call last):

File "", line 1, in 
user.buy(sh510050, price=2.100, amount=100)

NameError: name 'sh510050' is not defined

加上“”sh“”还是有问题

**Comment by shidenggui** [comment]
用 'sh510050'

**Comment by lyghid** [comment]
user.buy('sh510050', price=2.100, amount=100)
Out[21]: 
{'cssweb_code': 'error',
 'cssweb_msg': '证券代码长度不对',
 'cssweb_type': 'STOCK_BUY',
 'item': None}
