### ISSUE TITLE
华泰买ETF错误

### ISSUE THREAD

**Issue by lyghid** [shidenggui/easytrader#107]
user.buy('sh510050', price=2.100, amount=100)
Out[21]: 
{'cssweb_code': 'error',
 'cssweb_msg': '证券代码长度不对',
 'cssweb_type': 'STOCK_BUY',
 'item': None}

**Comment by lyghid** [comment]
user.buy('510050', price=1.100, amount=100)
Out[23]: 
{'cssweb_code': 'error',
 'cssweb_msg': '[251070][校验上海指定交易失败，上海的未指定户或者在委托托管股票类别不是X,1] [stock_account=A243423126,regflag=0]',
 'cssweb_type': 'STOCK_BUY',
 'item': None}

**Comment by lyghid** [comment]
好像是上海证券账号不对，交易提交给了另一个上海账号，可是我也没地方设置上海账号啊

**Comment by shidenggui** [comment]
如果你有多个上海帐号的话，可能默认的帐号会选择错误，这时候你需要在代码里面手动指定你对应的沪深帐号

**Comment by lyghid** [comment]
怎样手动选择？代码里那个位置改？

**Comment by shidenggui** [comment]
自己查看相关源码

**Comment by lyghid** [comment]
蒙食灯鬼大神提示，解决了华泰上海默认账户错误，谢谢大神。修改如下：
httrader.py中：
def __set_trade_need_info(self, json_data):
"""设置交易所需的一些基本参数
:param json_data:登录成功返回的json数据
"""
for account_info in json_data['item']:
if account_info['stock_account'].startswith('A'):
# 沪 A 股东代码以 A 开头，同时需要是数字，沪 B 帐号以 C 开头
if account_info['exchange_type'].isdigit():
self.__sh_exchange_type = account_info['exchange_type'] 
self.__sh_stock_account = account_info['stock_account']
if account_info['stock_account']== 'A111111111':#此处为我新添加，账号为原错误默认账号
self.__sh_stock_account ='A222222222' #此处为我添加，账号为实际交易账号
log.debug('sh_A stock account %s' % self.__sh_stock_account)
