### ISSUE TITLE
银河证券登陆不能

### ISSUE THREAD

**Issue by fayeshine** [shidenggui/easytrader#138]
据群里大家反映，银河应该是它验证码服务有识别是不是正常的浏览,过不了就不出验证码。
现在已经登陆不能了，求解决

**Comment by fayeshine** [comment]
@shidenggui

**Comment by shidenggui** [comment]
yh升级了验证码，好几个券商最近都在升级web端，要观察一段时间

**Comment by shidenggui** [comment]
暂时移除了yh的支持，不过代码还保留着
