### ISSUE TITLE
广发 加密的客户号 加密的密码

### ISSUE THREAD

**Issue by yssource** [shidenggui/easytrader#146]
你好, 谢谢你的项目.
对于广发用户来说, 很难弄到 加密的客户号 和 加密的密码. 你是如何实现的呢?
我尝试了 IE 控制台 跟踪 post 请求, 也没有找到 任何, username password 信息.

**Comment by shidenggui** [comment]
跟教程里类似，你可以试下 fiddler 之类的工具辅助
