### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by Chin-en** [shidenggui/easytrader#15]
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/90/bnqnyd2j2c70x1tb013tlff40000gn/T/pip-build-RBH8hv/easytrader

請問是什麼意思呢？謝謝

**Comment by neoctopus** [comment]
额 我也是刚刚学习中

2016-02-26 3:44 GMT+08:00 Chin-en <notifications@github.com>:

**Comment by shidenggui** [comment]
出现这种情况的需要  `pip install -r requirements` 安装下相关依赖
