### ISSUE TITLE
使用银河下单时，有一定概率下单不成功

### ISSUE THREAD

**Issue by zhoujz10** [shidenggui/easytrader#154]
而且也没有任何返回消息， 不知道该怎么判断下单是不是成功了。

如果下单成功了，会返回 trade response: {"orderid":"XXXXXX","ordersno":"XXXXXX"}这样的dict，但有时候下单不能成功， 我试图用response is None 和 'orderid' in response 来判断，但却判断不出来。

**Comment by shidenggui** [comment]
下单失败时银河的返回是什么？有没有更加详细的日志？

**Comment by zhoujz10** [comment]
我没有记录日志，但是在yhtrader.py里的__trade函数中有log.debug语句。我下单后这个语句都会打印出返回信息，如trade response: {"orderid":"XXXXXX","ordersno":"XXXXXX"}，但有时就不会打印这个，不知道为什么。不打印这个信息的时候，有时下单仍然成功，但有时就失败了。

**Comment by zhoujz10** [comment]
我在我的程序里加了一些调试语句，明天再看看。如果只有我遇到这个问题的话，那应该是我自己代码的问题。

**Comment by shidenggui** [comment]
需要更多信息

**Comment by zhoujz10** [comment]
我最近又观察了几天，平均6-7单就有1单下单不成功，没有任何返回值，就是不成功。也有一次有返回值，返回了失败信息，我并没有掉线，但重复下单三次仍然失败。有返回值的这个问题好解决，我可以让程序发个邮件告诉我下单失败，但没有任何返回值却又不报错我确实不知道该怎么调试。我怀疑是丢包了，券商没收到我的信息。请问我可以怎么调试呢？这个失败率有点高。之前在使用佣金宝的时候从未出现过这种现象。

**Comment by zhoujz10** [comment]
下单失败的情况没有明显的规律，有集合竞价也有正常交易之间，有卖单也有买单，有几单连着一起下其中一单失败了也有只下一单就失败了的情况。
