### ISSUE TITLE
目前各券商web交易端更新频繁，请问根据目前经验，预计easytrader对哪个券商支持较好？

### ISSUE THREAD

**Issue by wybhit** [shidenggui/easytrader#155]
目前各券商web交易端更新频繁，请问根据目前经验，预计easytrader对哪个券商支持较好？

**Comment by shidenggui** [comment]
我兼职银河的开户，主力维护银河。目前银河那边的人说还没收到银河要关闭web的消息。广发的话据说在测试新的web端，但是旧的还可以用

**Comment by zhangzheng88** [comment]
不能破解手机端的api吗？这样就不需要web端的支持了

**Comment by shidenggui** [comment]
@zhangzheng88  不懂逆向，欢迎会的人贡献

**Comment by zhnlk** [comment]
可以抓一下手机用的移动端接口，我这边先尝试一下~成功就把代码加上去😄

**Comment by kismeter** [comment]
银河已经收到消息要关Web了

**Comment by cszhe** [comment]
@kismeter 你从哪里收到的消息？

**Comment by shidenggui** [comment]
银河已关闭，还剩广发web，目前补充了银河客户端的解决办法

**Comment by matrixleon18** [comment]
广发今天已经有问题了。可能需要一些调整。

**Comment by shidenggui** [comment]
web端现在逐渐都关闭了，转向维护客户端为主
