### ISSUE TITLE
佣金宝的接口还没有关闭呀

### ISSUE THREAD

**Issue by 4ever911** [shidenggui/easytrader#162]
是哪儿有消息说网页接口要关闭， 目前看还能登陆使用，没有关闭呀。

几个网站的综合测试看了下，佣金宝的还比较快，都是json数据。

不继续支持了么？

**Comment by shidenggui** [comment]
之前登陆之后会提示11月30号关闭，不知道为什么没关，待观察

**Comment by 4ever911** [comment]
我打个电话问问客服看看
