### ISSUE TITLE
银河客户端目前不能查询 balance

### ISSUE THREAD

**Issue by niutao3** [shidenggui/easytrader#166]
AttributeError                            Traceback (most recent call last)
<ipython-input-22-996275a3cfc0> in <module>()
----> 1 user.balance

AttributeError: 'YHClientTrader' object has no attribute 'balance'

**Comment by shidenggui** [comment]
是的，目前没有实现这个方法，推荐使用银河web端

**Comment by niutao3** [comment]
感谢您的回复！
