### ISSUE TITLE
广发新网址迁移

### ISSUE THREAD

**Issue by fayeshine** [shidenggui/easytrader#168]
广发要逐渐搬迁到新网址 hippo.gf.com.cn，旧网址 trade.gf.com.cn将慢慢转移并关闭，希望能支持新网址的连接和开发

**Comment by shidenggui** [comment]
最近比较忙，暂无计划，欢迎pr

**Comment by li-dp** [comment]
简单看了一下，似乎是用websocket做的。没做过web开发，没有头绪啊

**Comment by fayeshine** [comment]
@shidenggui 之前听说有人可能会开发接口，要不先保留着这个issue等PR？

**Comment by OrnsteinLin** [comment]
我简单看了hippo的数据传输，似乎挺难搞。。而且，密码明文传输了，什么鬼

**Comment by happybeta** [comment]
不是，还没解决？

**Comment by happybeta** [comment]
不是吧，还没解决啊？

**Comment by CheneyWong** [comment]
旧版本已经不能下单了

**Comment by shidenggui** [comment]
无计划支持
