### ISSUE TITLE
华泰证券需要安装插件才可以登陆

### ISSUE THREAD

**Issue by hansxinjian** [shidenggui/easytrader#175]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='service.htsc.com.cn', port=443): Max retries exceeded with url: /service/login.jsp (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000242C24E1E10>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',))

**Comment by shidenggui** [comment]
华泰web已经关闭
