### ISSUE TITLE
长期运行问题

### ISSUE THREAD

**Issue by geniuszhe** [shidenggui/easytrader#177]
我在服务器端运行跑了好几天，就报密码尝试太多的错误，周末挂着也会报服务器断开连接之类的错误，我现在改进的方法就是每天执行定时任务，早上开盘前开启，下午停盘后关闭。补充一下：我follow的jh，使用yh
不知道是否改进这个问题，谢谢

**Comment by shidenggui** [comment]
长时间挂不稳定是券商服务器的关系，这些异常需要自己处理。每天定时开启关闭是比较好的
