### ISSUE TITLE
entrust等查询结果为乱码

### ISSUE THREAD

**Issue by tianxiawuzhe** [shidenggui/easytrader#184]
你好，我使用的py2.7.12环境，使用0.9.7版本，在执行use.entrust后，返回结果字典中key都变成了unicode编码，如下形式：
[{u'\u8bc1\u5238\u540d\u79f0': u'\u78b3\u5143\u7533\u8d2d', u'\u59d4\u6258\u65e5\u671f': u'20170308',.....不知是否遇到过？理论上讲key是英文字符，不应该是unicode才对呢，即使被编成unicode了，那也应该可以看出是英文的呀，求教求教~~~

**Comment by shidenggui** [comment]
服务器返回的key就是中文。`Python2` 显示的是 `unicode`，`Python3` 可以正常显示中文。推荐使用 `Python3`
