### ISSUE TITLE
雪球账号获取history报错

### ISSUE THREAD

**Issue by chenxing0407** [shidenggui/easytrader#186]
xq = easytrader.use('xq')
xq.prepare('xq.json')
print(xq.get_balance())
print (xq.history)

报错：
{'error_description': '', 'error_uri': '/cubes/rebalancing/history.json', 'error_code': '10022'}

**Comment by kanghua309** [comment]
雪球登录增加验证码了。怎么办呢

**Comment by shidenggui** [comment]
雪球现在加了滑块验证码，准备放弃维护了
