### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by fayeshine** [shidenggui/easytrader#187]
running develop
running egg_info
writing easytrader.egg-info/PKG-INFO
writing dependency_links to easytrader.egg-info/dependency_links.txt
writing requirements to easytrader.egg-info/requires.txt
writing top-level names to easytrader.egg-info/top_level.txt
error: package directory 'easytrader/thirdlibrary' does not exist

**Comment by kanaxu** [comment]
安装出错：linux(deepin) anaconda 4 python 3.6
command "python setup.py egg_info" failed with error code 1 in /tmp/pop-build-pn2jgc7d/easytrader/
