### ISSUE TITLE
广发命令行调用 python cli.py --get today_ipo_limit 错误

### ISSUE THREAD

**Issue by raywoocn** [shidenggui/easytrader#191]
请问是什么原因？
调用： python cli.py --get today_ipo_limit
返回如下错误，

Traceback (most recent call last):
  File "cli.py", line 41, in <module>
    main()
  File "C:\Python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 36, in main
    json_result = json.dumps(result, indent=4, ensure_ascii=False, sort_keys=True)
  File "C:\Python27\lib\json\__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "C:\Python27\lib\json\encoder.py", line 209, in encode
    chunks = list(chunks)
  File "C:\Python27\lib\json\encoder.py", line 442, in _iterencode
    o = _default(o)
  File "C:\Python27\lib\json\encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <bound method GFTrader.today_ipo_limit of <easytrader.gftrader.GFTrader object at 0x0413EE30>> is not JSON serializable

**Comment by shidenggui** [comment]
命令行这边有点bug，你替换 `cli.py` 的内容为下面,  然后使用 `python cli.py --do today_ipo_limit` 试试行不行。推荐还是直接在 `Python` 中调用

```python
# -*- coding: utf-8 -*-

import json
import better_exceptions
import click
import dill

import easytrader

ACCOUNT_OBJECT_FILE = 'account.session'


@click.command()
@click.option('--use', help='指定券商 [ht, yjb, yh]')
@click.option('--prepare', type=click.Path(exists=True), help='指定登录账户文件路径')
@click.option('--get', help='调用 easytrader 中对应的变量')
@click.option('--do', help='调用 easytrader 中对应的函数名')
@click.option('--debug', default=False, help='是否输出 easytrader 的 debug 日志')
@click.argument('params', nargs=-1)
def main(prepare, use, do, get, params, debug):
    if get is not None:
        do = get
    if prepare is not None and use in ['ht', 'yjb', 'yh', 'gf', 'xq']:
        user = easytrader.use(use, debug)
        user.prepare(prepare)
        with open(ACCOUNT_OBJECT_FILE, 'wb') as f:
            dill.dump(user, f)
    if do is not None:
        with open(ACCOUNT_OBJECT_FILE, 'rb') as f:
            user = dill.load(f)

        if get is not None:
            result = getattr(user, do)
        else:
            result = getattr(user, do)(*params)

        json_result = json.dumps(result, indent=4, ensure_ascii=False, sort_keys=True)
        click.echo(json_result)


if __name__ == '__main__':
    main()
```

**Comment by raywoocn** [comment]
按照你提供的方法，可以拿到数据了，非常感谢。

**Comment by chendch203** [comment]
你好，请问广发的gf.json如何配置？尝试各种办法都找不到加密后的用户名密码。
