### ISSUE TITLE
the installation of the latest version 0.11.11 will be failed with syntax error for “row. 账户额度”

### ISSUE THREAD

**Issue by tianshi-xiong** [shidenggui/easytrader#193]
syntax error for “row. 账户额度”

then I changed the for loop as below, and the installation is ok:
but not sure if it can work as I have no account now

 def auto_ipo(self):
        """
        自动打新
        :return: list(dict) dict 格式为 {'申购股票': 申购返回结果}
        """
        ipo_info, _ = self.get_ipo_info()
        ipo_info.fillna(0, inplace=True)

        res = []
        for index,row in ipo_info.iterrows():
            if row['账户额度'] <= 0:
                continue
            response = self.buy(row['代码'], row['价格'], row['账户额度'])
            res.append({
                row['名称']: response
            })
        return res

**Comment by shidenggui** [comment]
What's your Python version and platform ? I'm just test code on Python 3.5 with MacOS 10.12.4

**Comment by tianshi-xiong** [comment]
oh, sorry, miss that info, I use the python 2.7.10 with MacOS 10.11.3

**Comment by shidenggui** [comment]
updated by use `iterrows`
