### ISSUE TITLE
广发证券调用gftrader中today_ipo_limit返回值有问题

### ISSUE THREAD

**Issue by cystory** [shidenggui/easytrader#194]
下面是我用today_ipo_limit返回的数据：
{'total': 1, 'data': [{'branch_no': '1504', 'exchange_type_dict': '深圳', 'register_date': '20170414', 'init_date': '20170414', 'fund_account': '2009490', 'exchange_type': '2', 'enable_amount': '70500.00', 'client_id': 已隐藏, 'stock_account': '0104020906'}], 'success': True}
今天已经是4/17，怎么返回的日期是4/14？还有今天有三只新股，里面似乎没有包含申购上限的数据。Gftrader中的today_ipo_list测试没有问题

**Comment by shidenggui** [comment]
广发证券确定关闭web，不再提供支持
