### ISSUE TITLE
默认的 json 并没有 JSONDecodeError 

### ISSUE THREAD

**Issue by yzxh24** [shidenggui/easytrader#20]
webtrader.py 里有以下一段代码：
`except json.JSONDecodeError:`
但实际默认的 json 模块并没有 JSONDecodeError
只有 simplejson 才有
github不熟悉，没法提交我的修改，见谅

**Comment by shidenggui** [comment]
使用 `ValueError` 代替了 `JsonDecodeError` ，原因可见此链接  http://stackoverflow.com/questions/15170676/python-cannot-import-jsondecodeerror
