### ISSUE TITLE
能不能添加对中信建投证券的支持？

### ISSUE THREAD

**Issue by 4ever911** [shidenggui/easytrader#202]
Tushare里面有对老版本中信建投web版本的支持，里面都是json数据返回，但是那部分好像很久都没维护，也有一些bug。

现在中信建投官网做了一个新的web交易接口   https://e.csc108.com/jy/main

里面交互都是通过json数据，感觉应该比较容易支持，不知道是否可以添加对它的支持。

我个人可以提供账号做调试。

**Comment by shidenggui** [comment]
暂无计划，如果有兴趣的欢迎大家 pr

**Comment by zlq4863947** [comment]
pr啥意思？
