### ISSUE TITLE
代码在 crontab 下无法正常运行

### ISSUE THREAD

**Issue by yzxh24** [shidenggui/easytrader#21]
直接在命令行使用是没问题的，一旦加入到 crontab 里，代码就无法正常执行。

主要问题在于 `os.path.dirname(__file__)` 在 crontab 下并没有得到预期的文件路径，从而导致 json 配置文件无法被正常读取。

我目前的解决办法是把里面的路径全部替换成了绝对路径。

**Comment by shidenggui** [comment]
搜索了一下，发现是 `crontab` 的一个 `bug`，要修改的话比较麻烦，可能要考虑下。暂时可以用下面这个解决方案 
http://stackoverflow.com/questions/14886715/wrong-path-results-the-python-program-runs-using-crontab
