### ISSUE TITLE
银河 web 很快不能用了....

### ISSUE THREAD

**Issue by 4ever911** [shidenggui/easytrader#210]
尊敬的投资者：
      为进一步提升交易安全，我公司于2017年6月30日16时起停止提供WEB交易系统，您将无法通过该系统进行证券交易。本次暂停仅针对WEB交易系统，我公司提供的其它交易方式不受影响，为避免影响您的正常交易，建议请您使用我公司提供的其它交易方式（下载地址：http://www.chinastock.com.cn/yhwz/service/download.shtml）。
     若您对此有任何意见或建议，请您与您所在当地营业部联系或致电95551。 
     中国银河证券股份有限公司提醒您：股市有风险，入市需谨慎。

**Comment by shidenggui** [comment]
是的，后面会完善下客户端
