### ISSUE TITLE
持仓字符串解析问题

### ISSUE THREAD

**Issue by shenxingbei** [shidenggui/easytrader#213]
获取持仓的时候，有些证券名称是带空格的，比如"中 小 板"
df = pd.read_csv(reader, delim_whitespace=True)
字符串分割结果会有问题，导致返回的dict错乱了。
改成用sep='\t'分割就正常了。

**Comment by shidenggui** [comment]
close by a79b6b0a3855125310297ddecce15bf7878a95eb
