### ISSUE TITLE
银河客户端跟踪雪球组合失败

### ISSUE THREAD

**Issue by moment1102** [shidenggui/easytrader#223]
import easytrader
user = easytrader.use('yh_client')
user.prepare(user='我的银河账号', password='我的银河密码')
xq_follower = easytrader.follower('xq')
xq_follower.login(user='我的雪球账号', password='我的雪球密码')
xq_follower.follow(user, 'ZH973683', total_assets=100000)

一直跳出来
2017-07-21 16:08:35,288 [INFO] follower.py 54: 登录成功
>>> xq_follower.follow(user, 'ZH973683', total_assets=100000)
2017-07-21 16:08:35,390 [INFO] xq_follower.py 75: 开始跟踪策略: 1号乌龟
>>> {'error_code': '10022', 'error_description': '', 'error_uri': '/cubes/rebala
ncing/history.json'}
2017-07-21 16:08:35,454 [WARNING] follower.py 130: 无法获取策略 1号乌龟 调仓信息
, 错误: 'count', 跳过此次调仓查询
{'error_code': '10022', 'error_description': '', 'error_uri': '/cubes/rebalancin
g/history.json'}

**Comment by kanghua309** [comment]
雪球增加验证码了

**Comment by shidenggui** [comment]
雪球现在加了滑块验证码，准备放弃维护了
