### ISSUE TITLE
银河客户端连接报错：No module named win32api

### ISSUE THREAD

**Issue by tianxiawuzhe** [shidenggui/easytrader#225]
老师，不好意思，我还遇到了一个问题：我在更新完最新的easytrader后，按照中文文档“http://easytrader.readthedocs.io/zh/master/install/”里面写的，把系统设置 > 快速交易: 关闭所有的买卖，撤单等确认选项；系统设置 > 界面设置: 界面不操作超时时间设为 0；系统设置 > 交易设置: 默认买入价格/买入数量/卖出价格/卖出数量 都设置为 空；
都设置好了，然后我在python命令行环境里使用，发现直接报如下错误：
>>> import easytrader
>>> user = easytrader.use('yh_client')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/easytrader/api.py", line 36, in use
    from .yh_clienttrader import YHClientTrader
  File "/usr/local/lib/python2.7/site-packages/easytrader/yh_clienttrader.py", line 9, in <module>
    import win32api
ImportError: No module named win32api
我尝试安装pywin32，可是pip报找不到程序包呢，我在win7和linux下均试了，都报一样的错，是我应该安装其他别的程序包么？或者我的使用有问题？多谢多谢~~~

**Comment by tianxiawuzhe** [comment]
我下载的双子星云服务版V3.2.18，应该符合要求吧？

**Comment by fswzb** [comment]
要安装win32api

**Comment by allenwq** [comment]
同样的问题， linux 下还能安装win32api ?

**Comment by tianxiawuzhe** [comment]
同问，linux下如何安装win32api？我看程序包里都是些exe的文件，应该不能在linux上运行吧？

**Comment by tianxiawuzhe** [comment]
我看了下yh_clienttrader.py文件，看着好像如果使用银河客户端的功能，那么必须使用windows机器，而且还得先登录到客户端中？程序默认为自动打开客户端的登录框，好像并不会自动登录，像web方式一样，默默的连接和登录。向楼主求证。

**Comment by shidenggui** [comment]
linux 下没办法使用win32api，必须windows。自动登陆是可以的，不过有时候成功率不高就是了
