### ISSUE TITLE
auto_ipo不起作用

### ISSUE THREAD

**Issue by marzwu** [shidenggui/easytrader#239]
## env

OS: win
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.12.3

## problem
auto_ipo()运行后，打新界面一闪而过

## how to repeat
`    user = easytrader.use('yh_client')`
`    user.prepare('config/yh_client.json')`

`    user.auto_ipo()`
`    position = user.position`
`    entrust = user.today_entrusts`
`    balance = user.balance[0]`

**Comment by shidenggui** [comment]
你是在打新时间使用的吗？

**Comment by marzwu** [comment]
是的，交易时间用的，股票买入可以成功委托

**Comment by wuyongyi** [comment]
补充一下，yh的可以用，但是如果其中有一个标的申购指标是0则无法买入，看了代码此时直接返回到提示指标为0然后就关闭了，建议不要用select all而是只选择指标非0的，然后才执行一键打新

**Comment by marzwu** [comment]
我提交了一个pull request，修复了这个问题。
另外为什么我这里打新确认弹窗标题是“委托确认”，我的银河客户端是“中国银河证券双子星3.2”
