### ISSUE TITLE
连接广发客户端出错，返回数据索引不匹配

### ISSUE THREAD

**Issue by RobotJiang** [shidenggui/easytrader#240]
## env

OS: linux
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.12.3

## problem
我看了下出错的原因是，广发返回数据发生了改变，请将 gftrader.py 里面的常量 HOLDER_POS 从之前的 11 修改为 12 .
这个修改比较小，我就不提 request 了。
## how to repeat
连广发，稳定重现。

**Comment by shidenggui** [comment]
广发的web我记得现在已经关闭了吧？
