### ISSUE TITLE
委托买入出现异常，但是委托成功了

### ISSUE THREAD

**Issue by marzwu** [shidenggui/easytrader#241]
## env

OS: win
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.12.3

## problem
异常信息：
{'parent': <win32_element_info.HwndElementInfo - '', Afx:400000:843:0:5:0, 3211340>, 'top_level_only': False, 'backend': 'win32', 'control_id': 1365}

## how to repeat
银河客户端，一般买卖

**Comment by shidenggui** [comment]
我更新了交易等待小窗口弹出的时间，你可以看下有没有改善
