### ISSUE TITLE
华泰客户端卖出函数需要人工点击确定

### ISSUE THREAD

**Issue by Mingwang1986** [shidenggui/easytrader#248]
## env

OS: win10
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.12.3
华泰：V5.18.56

## problem
买入函数可以正常下单，但卖出函数只会将数据在华泰客户端填写好，但需要人工点击确认；
## how to repeat
用的华泰的桌面版本，buy（）函数可以正常挂单，但sell（）函数必须人工点击确认后，才可以提交下单

**Comment by shidenggui** [comment]
我这边到没有这个情况。你可以在设置里直接关掉买卖需要确认的弹窗
