### ISSUE TITLE
ElementNotFoundError

### ISSUE THREAD

**Issue by Zhangjiahong001** [shidenggui/easytrader#254]
## env

OS: win10
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.12.3

## problem
user.position的时候，总是报错ElementNotFoundError: {'process': 12324, 'backend': 'win32', 'title': '网上股票交易应用程序'}

**Comment by shidenggui** [comment]
更新了新版本，请更新然后再试下

**Comment by robinlin1973** [comment]
在最新版 easytrader==0.13.5，这问题仍然存在。

ElementNotFoundError: {'class_name': 'Button', 'control_id': 32812, 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '', Afx:400000:843:0:5:0, 462932>, 'backend': 'win32'}
