### ISSUE TITLE
银河证券客户端登陆的初始页面总是处于“精简页面”，导致找不到“网上股票交易系统5.0”这个线程

### ISSUE THREAD

**Issue by Zhangjiahong001** [shidenggui/easytrader#255]
## env

OS: win10
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.xx.xx

**Comment by shidenggui** [comment]
你的 easytrader不是最新版本吧，新版本在自动登陆后如果检测到精简模式的话会自动点击还原到正常模式
