### ISSUE TITLE
国金证券全能行证券交易终端 获取balance失败

### ISSUE THREAD

**Issue by foxbupt** [shidenggui/easytrader#260]
## env

OS: win10
PYTHON_VERSION: 2.7
EASYTRADER_VERSION: 0.13.1

## problem
在win10下用python 2.7, 折腾了半天，把easyutils的依赖干掉，安装functools32, 修改import functools改为import functools32 as functools后，总算能跑通了。
调用user.balance一直失败，异常信息是无法找到控件ID 1012对应的控件窗口。
用spy++获取了界面上的控件ID，可能是新版下单程序的控件ID有变更，修正了后调用正常。
附最新的控件ID配置如下：
 BALANCE_CONTROL_ID_GROUP = {
        '可用金额': 1016,
        '股票市值': 1014,
        '总资产': 1015,
        '可取金额': 3011
}

以上供作者参考，希望能fix更新到master上，供参考。
btw: 作者的工作相当棒，送上100个赞。如果能支持Python 2.7就更好了，大致看了下代码，ms只有用到Python 3的lru_cache。另外文档里建议补充下需要安装的依赖package。

**Comment by shidenggui** [comment]
以前支持 Python 2.7，但是兼容性代码太 ugly 了，后期全部移除了。
我看了下国金官网，他们的客户端并没有更新，然后我下载又看了下，控件id也没有变化。
不知道你这个版本是怎么回事
