### ISSUE TITLE
华泰客户端在提交买入请求时，由于输入完股票号后，价格会自动填写，会导致后面填写价格的时候变成在后面追加。

### ISSUE THREAD

**Issue by WoolenWang** [shidenggui/easytrader#263]
https://github.com/shidenggui/easytrader/blob/d39b4582ff04f4eaae93dad60c55e10d241e3606/easytrader/clienttrader.py#L348

就是因为输入完股票代码后，会默认出来一个价格，然后就导致后面的输入的价格数字不对。

![bug](https://user-images.githubusercontent.com/3388253/35482393-64788e64-046f-11e8-9251-4276607cdfeb.gif)

**Comment by WoolenWang** [comment]
噢，华泰客户端版本是 5.18.57

交易设置里面确实可以设置这个默认为空


为了易用，希望作者能做一点改进，自动设置或者是输入的时候先删了原来的字符

**Comment by shidenggui** [comment]
文档里面已经提示的很清楚了，如果改成程序逻辑的话，复杂度和不稳定性都会上升。
