### ISSUE TITLE
报错 object has no attribute 'message'

### ISSUE THREAD

**Issue by sqr1sqr** [shidenggui/easytrader#268]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx

## problem
![qq 20180224134131](https://user-images.githubusercontent.com/29884179/36626146-201f5e10-1968-11e8-892b-5cb0e13a4a8f.png)

**Comment by shidenggui** [comment]
fixed by 9db0bea56577796e6cbbf367b58e2a2fc48025c5
