### ISSUE TITLE
雪球登陆报错：遇到错误，请刷新页面后重试

### ISSUE THREAD

**Issue by asxzy** [shidenggui/easytrader#269]
## env

OS: mac
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.13.5

## problem
无法登陆雪球，debug返回信息
```[DEBUG] xqtrader.py 61: login status: 遇到错误，请刷新页面后重试```

反查到登陆所用API网址：https://xueqiu.com/user/login
人工登陆，返回错误：```图形验证码错误，请重新验证。```
登陆点，海外

~~现在不确定是雪球这个网址限制了海外登陆，还是雪球启用了新的验证码导致API失效。~~
update:
已用国内ip测试，easytrader和浏览器登陆均报错。请有条件的朋友帮忙测试一下https://xueqiu.com/user/login，看是个例还是雪球做了限制。

求解决方案

**Comment by cometcao** [comment]
这是早在一个月前雪球就加入了新的认证机制。 如果想要绕过需要用别的lib来进行自动化

**Comment by asxzy** [comment]
已用cookie解决
```
self._account.autologin = lambda : None
self._account.prepare("xq.json")
self._account.account_config = {
        "user": "",
        "password": "",
        "initial_assets" : 1000000,
        "portfolio_code" : "",
        "portfolio_market": "cn"
    } 
cookie = """your cookie here"""
cookie_dict = {}
for record in cookie.split(";"):
    key,value = record.strip().split("=",1)
    cookie_dict[key] = value
self._account.session.cookies = requests.utils.cookiejar_from_dict(cookie_dict)
```
等闲了我递交一个commit

**Comment by gongzhibin** [comment]
@asxzy 请问一下，你的cookie是怎样获取的？谢谢

**Comment by nbnc003** [comment]
@asxzy 求问具体解决办法？

**Comment by asxzy** [comment]
@nbnc003 请参考3楼代码

**Comment by gongzhibin** [comment]
@asxzy 已找到并解决，谢谢

**Comment by nbnc003** [comment]
@asxzy 抱歉，问个十分业余的问题，cookie我知道怎么获取，但是您的代码应该放在哪里？xqtrader下面的某个def下？还是在某个地方新建个py文件呢？我是py初学者，可能这个问题显得比较白痴，麻烦您了

**Comment by asxzy** [comment]
三楼代码是class的一部分，你可以批量删除掉self.并填写cookie，剩余代码中的account即为实例化后的easytrader对象。最近学业较重，没时间递交commit。

Yi
