### ISSUE TITLE
华泰客户端问题

### ISSUE THREAD

**Issue by szhu3210** [shidenggui/easytrader#271]
## env

OS: win10
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.13.5
华泰客户端：网上交易系统（专业版Ⅱ）V5.51 （更新日期：2018-01-26 24.0M）（下载链接（20180311）：http://www.htsc.com.cn/browser/softInfoAction.do?method=searchP&currentMenu=softInfo 中第一个）

## problem
测试中发现若干函数出现exception，目测GUI是没有点击到正确的菜单选项。可能和新版客户端修改了菜单有关。

## how to repeat
user.entrust
user.position

另外求一个稳定可用的华泰客户端版本，测试一下看看能否正常使用。

谢谢！

**Comment by shidenggui** [comment]
refer to #272 #270

**Comment by szhu3210** [comment]
谢谢！
