### ISSUE TITLE
旧版本同花顺客户端的下载链接，用来解决新版本同花顺客户端不支持复制的限制

### ISSUE THREAD

**Issue by shidenggui** [shidenggui/easytrader#272]
旧版本同花顺客户端的下载链接，用来解决新版本同花顺客户端不支持复制的限制

目前我手里就只有银河、华泰、国金、通用版同花顺的旧版本下载，如果大家有其他客户端的话也欢迎回复提供下载地址。

Changelog:

* 2018.07.01: 更新了银河的下载链接，现在银河支持通过另存为 `xls` 文件来获取 `grid` 信息了

## 下载链接

* 银河: [百度网盘](https://pan.baidu.com/s/1ByzfxcPRDtNEb6d8TQDTPw) 密码: ry4o
* 华泰: [百度网盘](https://pan.baidu.com/s/1bnJqfDH6P-ISn4_EGpqlvg) 密码: bpfk
* 佣金宝(国金): [百度网盘](https://pan.baidu.com/s/1sWHU-VQEwyaO_JTb_rjFMQ) 密码: xhs1
* 通用版同花顺:  [百度网盘](https://pan.baidu.com/s/1_p4k_pb1_6qmg5sdm9856g) 密码: k8en

**Comment by squall1988** [comment]
请问测试的环境是什么啊，在win10 下面解析国金证券的客户端的窗口我跑不通。

**Comment by Z0eDu** [comment]
你好， 请问还有银河旧版本的链接吗

**Comment by shidenggui** [comment]
最新版以及解决了，统一改为使用保存 xls 的模式，不再使用复制方式
