### ISSUE TITLE
ElementNotFoundError

### ISSUE THREAD

**Issue by robinlin1973** [shidenggui/easytrader#273]
## win10

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx

## easytrader==0.13.5
ElementNotFoundError: {'class_name': 'Button', 'control_id': 32812, 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '', Afx:400000:843:0:5:0, 462932>, 'backend': 'win32'}

## how to repeat
运行这问题就能重现

**Comment by shidenggui** [comment]
请使用 #272 里面的客户端
