### ISSUE TITLE
无法跟踪雪球组合

### ISSUE THREAD

**Issue by nbnc003** [shidenggui/easytrader#274]
## env

OS: win10 
PYTHON_VERSION: 3.65
EASYTRADER_VERSION: 0.13.7

## problem
使用` xq_follower.follow(user, 'ZH1298344', total_assets=10000)`指令后出现：
`{'error_description': '', 'error_uri': '/cubes/rebalancing/history.json', 'error_code': '10022'}
2018-04-17 21:51:30,247 [WARNING] follower.py 130: 无法获取策略 每年五倍 调仓信息, 错误: 'count', 跳过此次调仓查询`

跟踪了下组合页面的网络元素活动，发现URL应该是没变，不知道雪球加入了什么限制
求解决方案

**Comment by DruidWu** [comment]
您好，上面这个问题修复了吗

**Comment by jianjunhu** [comment]
无法获取策略 港股-XXXX 调仓信息, 错误: '证券代码', 跳过此次调仓查询

这个问题怎么解决？
