### ISSUE TITLE
同花顺撤单issue

### ISSUE THREAD

**Issue by xusguo** [shidenggui/easytrader#275]
## env

OS: win7
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.13.6

## problem
请教下大神：
use.buy  返回值为：  ｛‘message’，‘success’｝  而不是文档说的 result_no ，这样如果是撤单不容易找合同编号， 不知道是否我使用不当导致的， 请帮忙抽空看一下呢~
感谢

## how to repeat

import easytrader
broker = 'ths'
user = easytrader.use(broker)
user.connect(r'D:\同花顺软件\同花顺\xiadan.exe')
buy_res = user.buy(stock , price=price_buy, amount=amount_buy)
print (buy_res)

目前我的暂时方案是这样查询， 不过这样有个问题是today_entrusts 后面会比较多，数据量大系统会经常提示openclipboard fail

entrusts = user.today_entrusts
print(entrusts)
for dingdan in (entrusts):
       if(dingdan['备注'] == '未成交' and dingdan['证券代码'] == stock and dingdan['操作'] == '买入'):
                handle_cancel[stock] = dingdan['合同编号']
                print("for cancel",stock,handle_cancel[stock])

望大神指教一下，感谢~

**Comment by shidenggui** [comment]
系统可以配置是否返回成交回报。如果没配的话就是 `{"message":  "success"}`
