### ISSUE TITLE
银河下单客户端的title 不是‘网上股票交易系统5.0’ 导致的报错

### ISSUE THREAD

**Issue by sanjumsheng** [shidenggui/easytrader#278]
## env

OS:  win10 
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.13.8

## problem
user.prepare 之后 无论是调user.banlace 还是user.position还是user.buy都是报错:ElementNotFound:{'title:'网上股票交易系统5.0',backend';'win32','process':16872},

## how to repeat

银河证券最新版本的3.2.18,登陆上之后使用easytrader 报如上错误。

哪个大神帮忙看下，谢谢！

**Comment by sanjumsheng** [comment]
用了老大提供的银河客户端的版本的可以了，但是银河客户端的获取不到balance，这个很蛋疼，没法根据balance 仓位来买入特定的票。

**Comment by shidenggui** [comment]
用了我的客户端版本还是获取不到 balance ？

**Comment by sanjumsheng** [comment]
获取不到哦，balance 直接报错，position 是空的数组，今天用了通用版的同花顺也是一样的，请问老大这是哪里的问题呢，现在只有buy能用，查询委托得到的都是空数组[].
