### ISSUE TITLE
通用版同花顺客户端下单没法调起来

### ISSUE THREAD

**Issue by sanjumsheng** [shidenggui/easytrader#280]
## env

OS: win7
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.13.9

## problem
使用的#272 中的同花顺，下单委托界面也已经打开，但是用user.connect(r'C:\同花顺软件\同花顺\xiadan.exe')
报错，显示ProcessNotFoundError:Process "C:\同花顺软件\同花顺\xiadan.exe" not found.

## how to repeat
换了不同的电脑，不同的同花顺客户端都是这样。求救，谢谢。

**Comment by sanjumsheng** [comment]
又重新试了老大发的客户端，可以了

**Comment by cw3120** [comment]
user = easytrader.use('ths')
user.connect(r'C:\\同花顺软件\\同花顺2\\xiadan.exe')

显示错误：py:1064: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
我用的老大发的客户端也不行，系统是win10，谢谢。
