### ISSUE TITLE
通用版同花顺客户端查询balance,today_entrusts等调起来的界面错误问题

### ISSUE THREAD

**Issue by sanjumsheng** [shidenggui/easytrader#281]
## env

OS:  win10 
PYTHON_VERSION: 3.6.5
EASYTRADER_VERSION: 0.13.9

## problem
使用balance方法掉漆的系统去选中的不知道怎么回事是撤单[F3]，同时还报错：pywinauto.timings.TimeoutError，而today_entrusts则选中吊起的是市价委托的买入按钮，导致返回的是[]。position 要先选中查询[F4]再代码调用时自动选中的是撤单[F3]，返回的也是买入未成交的数据。请问大神，同花顺客户端的是不是搞错了，还是我哪里设置的不对，谢谢。

**Comment by shidenggui** [comment]
你是什么券商？

**Comment by sanjumsheng** [comment]
@shidenggui 万联证券和平安证券都有，还有同花顺这里调用sell方法调起来去自动操作的居然是卖出操作。为什么呢？其中万联证券我卖出操作是真实有持仓该个股的，但是结果是买入操作。平安证券我没有该个股，调用sell 也是买入操作。操作时间是今晚十一点。望能得到您的答复，他日若成功，必重谢。谢谢

**Comment by shidenggui** [comment]
通用同花顺的菜单应该是每个券商不同，这样的话适配很麻烦，目前只能自己大家适配了。如果有兴趣的，适配好了可以发 `PR` 给我

**Comment by sanjumsheng** [comment]
要适配的话，请问如何获取同花顺上该券商的这个对应的余额和卖出的字段是哪个呢？谢谢

**Comment by shidenggui** [comment]
@sanjumsheng  你需要看下这个券商的菜单路径是什么？具体需要修改源码
