### ISSUE TITLE
银河客户端跟踪雪球组合时希望加入滑点功能

### ISSUE THREAD

**Issue by iheero** [shidenggui/easytrader#282]
在使用银河客户端跟踪雪球组合时，根据雪球组合调仓发出的价格（price）进行[限价下单]，这会导致买入和卖出时不能及时成交。建议加入滑点功能：如设置滑点为0.5%，则买入时[调整后的下单价格]为price*(1+0.5%)，卖出时[调整后的下单价格]为price*(1-0.5%)。

**Comment by zhoubeiqing** [comment]
这个功能在业务层面实现比较好吧

**Comment by shidenggui** [comment]
close by dcdb48cfd781dd406ff1b66af64155a1699728c1
