### ISSUE TITLE
银河客户端5.11更新后，老版本不能使用

### ISSUE THREAD

**Issue by iheero** [shidenggui/easytrader#284]
银河客户端更新后，老版本登陆后已经不能出现交易界面，使用新版本客户端目前有以下问题：
1.无法自动登陆客户端
2.无法获取balance及position等参数调用，adjust_sell失效

**Comment by iheero** [comment]
考虑的解决方案：
1. 暂时考虑手动登陆。
2. 考虑到adjust_sell是实操中重要的功能，而新版本银河客户端已无法获取balance和position，建议通过新建文档用于在每天开盘前手动录入持有的各支股票代码及可用股数。交易指令发出时，将卖出股票代码和股数与事先录入的数据相比对，若指令的卖出股数大于事先录入的数据，则按事先录入数据的可用股数下单；反之则按指令股数下单。
（本问题发生在用银河客户端自动跟踪雪球组合时）

**Comment by iheero** [comment]
问题2的另一种解决方案：

每一次交易记录都保存在「log文件」中。每一次发出买或者卖的指令时，都往log文件写入交易的时间、方向、股票代码和交易的股数等，并自动统计和计算log文件中各股票的代码及可用股数（考虑T+1规则，当日记录为拥有股数，次日调整为可用股数）。将log文件作为虚拟持仓看待。

卖出交易指令发出时，将卖出股票代码和股数与log文件中的记录相比对，若指令的卖出股数大于log文件中的可用股数，则按log文件中的可用股数下单；反之则按指令股数下单。

**Comment by shidenggui** [comment]
close by e273e3fe07a2932d6ac830e621b30b7ccff69968
具体见 #270
