### ISSUE TITLE
通用版同花顺客户端查询balance 成交后没有自动刷新

### ISSUE THREAD

**Issue by WangMingyuan** [shidenggui/easytrader#288]
## env

OS: win7
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 最新版本
BROKER_TYPE: ths

## problem
委托成交后 资金股票界面没有自动刷新  在软件中设置了也不管用 能不能在easytrader里触发刷新呢
## how to repeat
资金股票界面
委托下单
下单成交
资金股票界面数字没有更新

**Comment by shidenggui** [comment]
你可以手动调用下 `user.position` 然后再调用 `user.balance` 进行刷新
