### ISSUE TITLE
跟踪聚宽会出现失败

### ISSUE THREAD

**Issue by nbnc003** [shidenggui/easytrader#289]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## how to repeat
1.跟踪聚宽一段时间（没具体测试，大概是30分钟左右）会出现由于访问次数过多被聚宽拒绝访问的提示，然后跟踪就此失败。
2.启动银河证券客户端，在交易界面登陆后无法自动将交易界面还原，导致程序出错，自动退出

**Comment by shidenggui** [comment]
1. `jointquant` 的问题，他们 `api` 限制的太死了，你可以用 `ricequant` 等其他平台
2. 我这边目前可以正常还原，没法复现
