### ISSUE TITLE
银河客户端查看账户和交易信息都无法获取到数据

### ISSUE THREAD

**Issue by zhoubeiqing** [shidenggui/easytrader#291]
## env

OS: win10
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.13.7
BROKER_TYPE: gj / ht / xq / xxx

## problem
银河客户端查看账户和交易信息都无法获取到数据,查看config/client.py少了BALANCE_CONTROL_ID_GROUP变量

**Comment by shidenggui** [comment]
close by e273e3fe07a2932d6ac830e621b30b7ccff69968
具体见 #270
