### ISSUE TITLE
python的user.balance如何才能每n秒实时获取最新的资产数据

### ISSUE THREAD

**Issue by littlefunfunfun** [shidenggui/easytrader#297]
## env

OS: win7/
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.15.0
BROKER_TYPE: ths

## problem
你好，请问为何我用user.balance得到资产信息一直都是第一次获取的资产信息，不会实时更新，需要去手动刷新同花顺才可以获得新的资产信息，前面看到类似问题说用手动调用user.potion是如何手动调用的呢？求解答，谢谢大神！！
## how to repeat
所以在交易过程中，python如何才能实时每n秒地获取到最新的资产信息？？

**Comment by shidenggui** [comment]
加了 `user.refresh()` api, close by ec53abf5b9bdbe0aaec03e627d4997e1a27eba7d
