### ISSUE TITLE
跟踪雪球组合时，同一天内对同一标的进行方向操作时存在BUG

### ISSUE THREAD

**Issue by iheero** [shidenggui/easytrader#298]
如：
10：00，雪球组合卖出100股股票A，easytrader执行操作「卖出100股股票A」，正确。
10：30，雪球组合买回100股股票A，easytrader执行的命令为「卖出100股股票A」，方向反了，存在BUG。

**Comment by shidenggui** [comment]
close by 619aa066103c9bc97fd2ee0099b2f26439f0a805
