### ISSUE TITLE
在华泰证券中，撤销委托无法成功。

### ISSUE THREAD

**Issue by wyxr** [shidenggui/easytrader#311]
## env

OS: win7
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: ht 

## problem
在华泰证券中，撤销委托无法成功。
返回显示：
{'message': '委托单状态错误不能撤单, 该委托单可能已经成交或者已撤'}
查询账户，该笔委托，实际上并没有成交
```
委托日期	证券代码	证券名称	操作	委托价格	委托数量	委托时间	成交数量	成交均价	合同编号	交易市场	股东帐户	备注	
20181112	510900	H股ETF	买入	1.103	100	10:20:38	0	0.000	11838	上海Ａ	A352030136	已报(买卖)	
```
麻烦问一下，这种问题应该怎么解决，其它的倒是没有什么问题。

**Comment by wyxr** [comment]
已经修改好了，修改cancel_entrust方法即可
 def cancel_entrust(self, entrust_no):
        self.refresh()
        for i, entrust in enumerate(self.cancel_entrusts):
            if (
                entrust[self._config.CANCEL_ENTRUST_ENTRUST_FIELD]
                == entrust_no["entrust_no"]
            ):  # entrust[self._config.CANCEL_ENTRUST_ENTRUST_FIELD]  == entrust_no
                self._cancel_entrust_by_double_click(i)
                return self._handle_pop_dialogs()
        return {"message": "委托单状态错误不能撤单, 该委托单可能已经成交或者已撤"}

**Comment by shidenggui** [comment]
这个应该是你传的 entrust_no 的问题，这里应该传的是委托单号，你直接把买卖返回的字典传入了。
