### ISSUE TITLE
华泰客户端报ElementNotEnabled异常

### ISSUE THREAD

**Issue by pacsicd** [shidenggui/easytrader#312]
## env

OS: win7
PYTHON_VERSION: 3.7.1
EASYTRADER_VERSION: 0.18.2
BROKER_TYPE: ht, 华泰网上证券委托系统V5.18.62

## problem
点击按钮 “全部选中”， 客户端没有选中下面的列表，“申购“ 维持灰选状态，导致无法打新股。该问题为偶发问题，出现的概率在50%左右，会报下面的异常。

    #-----------------------------------------------------------
    def verify_enabled(self):
        """
        Verify that the element is enabled

        Check first if the element's parent is enabled (skip if no parent),
        then check if element itself is enabled.
        """
        if not self.is_enabled():
            raise ElementNotEnabled()

## how to repeat
我有4个华泰账户，写了一个循环去做，出现的概率还是比较高。

**Comment by shidenggui** [comment]
你的意思是程序点击按钮 “全部选中”，实际却没生效吗？是不是界面还没刷新完毕，程序就尝试去发送点击事件，你看看能不能在点击的代码前加个 sleep，多 sleep 一段时间再点击，看会不会还出现这种问题。
