### ISSUE TITLE
运行报错：

### ISSUE THREAD

**Issue by wanghongliang** [shidenggui/easytrader#313]
## env

OS:  win10 
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: last
BROKER_TYPE:  ht  

## problem
运行报错：
    self.slippage: float = 0.0
                 ^
SyntaxError: invalid syntax

代码：
import easytrader
user = easytrader.use('ht_client')
user.prepare(user='XXXX', password='XXXX', comm_password='XXX')

print( user.balance )

**Comment by shidenggui** [comment]
Python 3.6
