### ISSUE TITLE
验证码识别url无法访问

### ISSUE THREAD

**Issue by zhoubeiqing** [shidenggui/easytrader#314]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
此网址无法访问
http://yh.ez.shidenggui.com:5000/yh_client
## how to repeat
银河客户端需要验证码

**Comment by shidenggui** [comment]
原有服务器到期了没有续费被释放了，等我有空把服务迁移到新的服务器。

**Comment by zhoubeiqing** [comment]
如果需要可以先使用我的服务器进行识别

**Comment by hgs1** [comment]
是否有进展，卡在了验证码环节

**Comment by zhoubeiqing** [comment]
> 是否有进展，卡在了验证码环节

木有😄

**Comment by shidenggui** [comment]
已经修复了
