### ISSUE TITLE
保存持仓信息时有几率出现找不到路径的错误信息

### ISSUE THREAD

**Issue by iheero** [shidenggui/easytrader#317]
用银河客户端配合easytrader跟踪雪球的组合，在处理adjust_sell_amount，保存为csv文件的时候，有时会出现找不到路径的错误导致保存失败。因为保存失败的对话框优先于查询持仓的界面，所以无法再执行查询持仓的操作，之后easytrader会一直报错影响后面的交易。
建议新增一种比对方式：只在程序启动时执行一次查询持仓，并保存覆盖为特定名字的csv，之后每次执行adjust_sell_amount的时候与它比对，而不是每一次执行卖出操作时都查询一次。因为中国的市场当天买，当天不能卖，所以当天可用的股票和可用的股数是固定不变的。

**Comment by shidenggui** [comment]
close by efb7f3d896aa12031d5ef58e44904382ffcc50d1
