### ISSUE TITLE
华泰下单系统，获取持仓时出错

### ISSUE THREAD

**Issue by lyghid** [shidenggui/easytrader#319]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
系统查找不到'查询[F4]’菜单，当需要找这个菜单时，错误的定位到’新股申购‘菜单

**Comment by Earthson** [comment]
win10上好像有问题，也有可能是分辨率导致的。click操作不对。换select就行了。不确定修改后的兼容性

https://github.com/shidenggui/easytrader/blob/master/easytrader/clienttrader.py#L341

**Comment by OscarShen** [comment]
非常感谢，将 click() 改为 select() 完美解决，环境为 win10 高分屏 125%缩放，海通证券同花顺版本。
