### ISSUE TITLE
您好,我想知道这个插件是否支持后台操作?

### ISSUE THREAD

**Issue by xzm1274913976** [shidenggui/easytrader#320]
## env

OS:  win10 

## problem
之前制作的游戏脚本使用的大漠组件+易语言可以实现后台自动化操作软件,想使用python制作相同功能,但是网上全是前台操作的案例,根据 https://www.v2ex.com/t/419147 本页面的推荐者看到 easytrader 这个项目,我想知道您是怎样实现窗口的后台操作的,具体应该查看那部分源码... 跟踪了一下有点懵逼. 多谢..

**Comment by shidenggui** [comment]
基于 pywinauto 实现的，你可以查看该库的文档。
