### ISSUE TITLE
在同花顺环境下自动打新会出现 验证码环节

### ISSUE THREAD

**Issue by caibitim** [shidenggui/easytrader#322]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
最新版本，环境各个方面都没问题。在同花顺环境下自动打新会出现 验证码环节。提示您正在拷贝数据，为保证数据安全，要输入验证码才行。

**Comment by shidenggui** [comment]
最新版已经修复
fix by #354
