### ISSUE TITLE
远程桌面登录云主机运行问题

### ISSUE THREAD

**Issue by ctguxp** [shidenggui/easytrader#324]
远程桌面登录云主机运行，是不是远程桌面退出后，鼠标键盘就锁定了，然后就无法下单了？如何解决

**Comment by pacsicd** [comment]
这个是远程桌面的问题，你可以用百度搜索一下 EnableCloseRDP.bat 的文件，弄下来后，如要退出远程桌面时，点击这个退出，就可以在后台用定时任务运行了。
