### ISSUE TITLE
点击的事件时常失效。

### ISSUE THREAD

**Issue by shizhengwen** [shidenggui/easytrader#325]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
我在吃用下委托的时候user.buy(...)或user.sell(...)发现有概率的买入或卖出这个按钮没有点下去，貌似只是从上面划过去了。但是这个问题不是每次都出现，当出现的时候那后面需要下的单都下不进去了。

给我的感觉是pywinauto这个的点击没用上
我用的是5.0的同花顺客户端，

**Comment by shizhengwen** [comment]
@sanjumsheng

**Comment by shizhengwen** [comment]
@shidenggui

**Comment by daliang0222** [comment]
我也遇到了这个问题 现在解决了吗 兄弟 @shizhengwen

**Comment by daliang0222** [comment]
大佬 能否帮忙看看吗， 时常点击事件失效， 按钮点击红色，实际没有下单成功，没有确认弹窗 @shidenggui

**Comment by sanitizer84** [comment]
python目录\Scripts\下面有一个 pywinauto_postinstall.py，这个要手工在管理员权限的命令行执行一下，要向系统目录copy一些dll
我昨天在surface go碰到“查询[F4]”定位不对的情况，今天执行了这个就好了。估计你这个也是这个问题
