### ISSUE TITLE
有没有能保持客户端一直在线的方法

### ISSUE THREAD

**Issue by hmxweg** [shidenggui/easytrader#326]
华泰客户端长时间不登录会失效，有没有能保持客户端一直在线的方法。目测refresh这个方法无效。使用JSON重登太慢，不现实

## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

**Comment by sanitizer84** [comment]
超时时间设置为0啊，使用说明上有讲
