### ISSUE TITLE
优化cancel_entrusts速度

### ISSUE THREAD

**Issue by izhangmh** [shidenggui/easytrader#327]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
为了刷新撤单列表，cancel_entrusts函数需要先切换到买入，再切回来。
能不能直接在撤单界面直接通过F3刷新呢？
@shidenggui

**Comment by shidenggui** [comment]
你可以尝试下，当时是用的统一的刷新方法，并没有针对性的做优化，因为怕不同券商之间不兼容。
