### ISSUE TITLE
银河客户端会跳出营业部公告或者其他一些公告

### ISSUE THREAD

**Issue by araura2000** [shidenggui/easytrader#335]
## env

OS: win server 2016
PYTHON_VERSION: 3.7
EASYTRADER_VERSION: 0.18.4
BROKER_TYPE: yh

## problem
银河客户端会跳出营业部公告等资讯弹窗导致余额，持仓及其他信息获取失败。可否增加检查并关闭弹窗功能？

**Comment by shidenggui** [comment]
最新版已经修复
fix by #354
