### ISSUE TITLE
如何查看同花顺客户端5.0相关按钮的CONTROL_ID

### ISSUE THREAD

**Issue by daliang0222** [shidenggui/easytrader#338]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

**Comment by daliang0222** [comment]
winspy

**Comment by AnYeMoWang** [comment]
@daliang0222 可以联系一下么？我也遇到了不知道如何获取control_ID的问题
