### ISSUE TITLE
prepare function, error 'No such file or directory: 'result.txt''

### ISSUE THREAD

**Issue by Chin-en** [shidenggui/easytrader#34]
Hi,

When I use 

user.prepare('ht.json')

It shows
[2016-03-29 11:05:25.947000] DEBUG: helpers.pyc: java detect result: '{' is not recognized as an internal or external command,
operable program or batch file.
'tesseract' is not recognized as an internal or external command,
operable program or batch file.
'export' is not recognized as an internal or external command,
operable program or batch file.
IOError: [Errno 2] No such file or directory: 'result.txt'

Is there any file I miss? I install easytrader through pyCharm. Is that okay? Thanks.

**Comment by shidenggui** [comment]
Are you using easytrader with windows and py2.7 ? This is a bug on windows with py2.7, because py2.7's commands.getoutput can't work on windows.I'll fix it later

**Comment by Chin-en** [comment]
Yeah.... So should I use python3?

**Comment by shidenggui** [comment]
Yes.Best to use python3.5

**Comment by Chin-en** [comment]
Thanks. Fixed.

**Comment by Chin-en** [comment]
Can I set a timestamp when I use buy() function?

**Comment by shidenggui** [comment]
No plan to support this feature. You can do it your self

**Comment by shidenggui** [comment]
fix by bbd1678e8f20580cfb80ed94570a8e18e85f71eb
