### ISSUE TITLE
华泰新版下单软件v5.18.66 在需要拷贝时弹出输入验证码提示框

### ISSUE THREAD

**Issue by lyghid** [shidenggui/easytrader#344]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## how to repeat

![image](https://user-images.githubusercontent.com/18131515/64060054-17055a00-cbfa-11e9-9283-d9dfb70bb2e6.png)

**Comment by shidenggui** [comment]
目前只能通过使用旧版本规避。

**Comment by izhangmh** [comment]
> 目前只能通过使用旧版本规避。

前几天我的华泰开始强制升级了，老版本取不到balance。不知道是不是普遍限制。
