### ISSUE TITLE
不支持 Mac 吗？

### ISSUE THREAD

**Issue by jinyuyoulong** [shidenggui/easytrader#347]
## env

OS: mac 
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
不支持 Mac 吗？如果不支持Mac 可否在 readme中声明一下。
## how to repeat
安装失败，无法安装依赖 pywin32。

**Comment by shidenggui** [comment]
股票软件没有 Mac 版本

**Comment by wanminny** [comment]
有mac 版本啊。。。

**Comment by firefeifei** [comment]
股票关键mac版本的很多
