### ISSUE TITLE
user.buy的返回结果有时是{"message": "success"}有时是{'entrust_no': 'xxxxxxxx'}

### ISSUE THREAD

**Issue by whogiawho** [shidenggui/easytrader#348]
## env

OS: win10
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: ths

## problem
usage文档注 “系统可以配置是否返回成交回报”
其实这不是个配置的问题
而是处理popup dialog流程不适当

## how to repeat
使用同花顺客户端，反复call user.buy，然后观察返回结果
使用以下代码：
```
sXiaDanFile=r'd:\Program Files (x86)\jyzqths\xiadan.exe'; 
import easytrader; 
user = easytrader.use('ths'); 
user.connect(sXiaDanFile); 
from easytrader import grid_strategies; 
user.grid_strategy = grid_strategies.Xls;
d = user.buy(stockCode, price=price, amount=amount)
print(d)
```
解决方法：
clienttrade.py的_handle_pop_dialogs负责处理popup dialog的原流程是：
```
        while self._is_exist_pop_dialog():
            title = self._get_pop_dialog_title()

            result = handler.handle(title)
            if result:
                return result
        return {"message": "success"}
```
可见这是一个循环，具体到user.buy，会依次出现两个dialog，“委托确认”和“提示”
如果在处理“委托确认”之后，“提示”弹出的时间晚于代码处理的时间，那么上述while循环就会退出，所以返回{"message": "success"}，这不是期望的结果
期望的结果应该总是返回{'entrust_no': 'xxxxxxxx'}
应该在handler.handle(title)后加入代码循环等待“提示”dialog出现，如下：
```
            result = handler.handle(title)
            #wait until "提示" appears
            if title ==  "委托确认" or title == "提示信息":
                while True:
                    bExist = self._is_exist_pop_dialog()
                    if(bExist==False):
                        self.wait(0.1)
                    else:
                        break
                continue
            if result:
                return result
```

**Comment by shidenggui** [comment]
这个提示我记得是可以关掉的，所以当时为了兼容关掉的情况，在一定时间没弹出就直接返回。我后期重新思考下处理 pop dialog 的逻辑，现在还是有点不完善

**Comment by whogiawho** [comment]
> 这个提示我记得是可以关掉的，所以当时为了兼容关掉的情况，在一定时间没弹出就直接返回。我后期重新思考下处理 pop dialog 的逻辑，现在还是有点不完善

原来usage文档里说的系统是指同花顺系统，不是easytrader

返回合同号有时是必须的，因为需要跟踪合同号来确认该笔提交是否成交
