### ISSUE TITLE
华泰证券下单软件强制更新之后，复制剪贴板增加了强制验证码

### ISSUE THREAD

**Issue by kezida** [shidenggui/easytrader#350]
## env

OS:  win10 
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.13.14
BROKER_TYPE: ht

## problem
华泰证券下单软件（专业版II，V5.18.66）2019年10月强制更新之后，复制剪贴板增加了强制验证码，希望解决这个问题。

## how to repeat
使用华泰证券下单复制剪贴板

**Comment by matrixleon18** [comment]
How to repeat:
1. 打开华泰网上证券委托系统，
2. 登陆以后
3. 在键盘上按下 Ctrl+C ，形成一个复制事件
4. 系统会弹出一个窗口“检测到您正在拷贝数据，为保护您的账号数据安全，请先输入验证码”
5. 手动输入验证码，再按下“确定”按钮，数据会被成功复制。如果按下“取消”按钮，数据无法复制。

**Comment by hyfjjjj** [comment]
我用的版本较老，但是原理是一样的，找到了一个简单的方法，修改easytrader代码：
1.  找到发送 copy 事件的代码（有类似type_keys('^A^C')代码的地方），通过类似  _is_exist_pop_dialog 判断是否有验证码弹出框
2. 如果有弹出框，调用 all_ctrls = list(self._app.top_window().descendants())获取弹出框的所有子控件，其中 all_ctrls[0] 为“确认”按钮，all_ctrls[3]为验证码图片，all_ctrls[6]为验证码输入框
3. 使用 all_ctrls[3].capture_as_image().save('./code.png') 能够将验证码保存为本地图片
4. 使用 baidu-aip 的文字识别识别验证码（免费用户可以使用，安装使用非常简单，识别速度也非常快），百度图片识别文档：http://ai.baidu.com/docs#/OCR-Python-SDK/top
5. all_ctrls[6].type_keys('百度识别的验证码') ，自动输入验证码
  all_ctrls[0].click()  自动点击“确定”按钮
  time.sleep(0.1) 可以sleep一下，确保已经保存到剪贴板
6. 现在就可以返回正确的复制数据了

**Comment by eric1lubow** [comment]
代码有实现使用保存csv 来拷贝数据，可以修改clienttrader.py 里的51行，把调用copy 改成保存xls。
可以参考这个：
https://github.com/hielf/easytrader/commit/a2d1e4ddf523242756bdd63a3049fc6667dc9954

**Comment by matrixleon18** [comment]
[cid:5ea7baf4-4a96-494d-a360-f0f1795c0eca]
________________________________

**Comment by matrixleon18** [comment]
@eric1lubow
你的办法有效，也可以参照yh_clienttrader.py的修改方法，
在ht_clienttrader.py的第5行，加上这样部分：
from . import grid_strategies,
在ht_clienttrader.py的第9行，加上这样一句:
grid_strategy = grid_strategies.Xls

**Comment by jjandnn** [comment]
@matrixleon18,原本用了很繁琐的方式，，就是没想到去银河哪里看一眼，呵呵，cool，脑经急转弯。

**Comment by shidenggui** [comment]
最新版已经修复，改为使用 xls 方式解决
fix by #354
