### ISSUE TITLE
有时卖出操作的price会跟在当前price的后头，而不是覆盖

### ISSUE THREAD

**Issue by whogiawho** [shidenggui/easytrader#352]
## env

OS: win10
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.18.4
BROKER_TYPE: ths

## problem
做卖出操作（卖出价是22.92）时，当前price是22.76（这个价格在输入security code由ths自动填写），在卖出价格框内应当是22.92，实际上是22.7622.92
原因是似乎是easytrader和ths同时操作edit control text？

这种情况有时有，有时没有

## how to repeat
F1切换到买入
然后做卖出操作
```
d = user.sell(stockCode, price=price, amount=amount)
```
反复直到bug出现

解决方法：
调换输入price和amount的次序
```
        self._type_keys(self._config.TRADE_AMOUNT_CONTROL_ID, str(int(amount)))
        self._type_keys(
            self._config.TRADE_PRICE_CONTROL_ID,
            easyutils.round_price_by_code(price, code),
        )

```

**Comment by shidenggui** [comment]
你要在同花顺里面关闭价格自动填充，文档里应该有提到。
