### ISSUE TITLE
同花顺老大提供的版本2019-11-15日开始不能用了，求助

### ISSUE THREAD

**Issue by sanjumsheng** [shidenggui/easytrader#353]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
老大提供的下载链接里的同花顺v8.70.42，在2019.11.15日开始不能用了，复制粘贴用不了了，求助。
![11](https://user-images.githubusercontent.com/6977280/68860619-dad79500-0724-11ea-909a-de9fe6778c37.png)

@shidenggui  谢谢

**Comment by lynic** [comment]
遇到了同样的问题

**Comment by shidenggui** [comment]
可以改用最新版本，只不过 copy 的策略不能用了，要改成 xls，最近会发一个修复版本。

**Comment by sanjumsheng** [comment]
> 可以改用最新版本，只不过 copy 的策略不能用了，要改成 xls，最近会发一个修复版本。

谢谢，买卖时copy不过去了，期待新版本。谢谢

**Comment by shidenggui** [comment]
最新版已经修复
fix by #354
