### ISSUE TITLE
华泰证券客户端交易成功弹窗导致下笔交易失败

### ISSUE THREAD

**Issue by ymsz2003** [shidenggui/easytrader#355]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE:  ht 

## problem
华泰证券客户端卖出成功后会弹窗提示，会导致下一笔卖出的确认按钮定位不到，造成下一笔卖出不成功

**Comment by shidenggui** [comment]
这个我记得是可以在同花顺的设置里关闭提示的。

**Comment by shidenggui** [comment]
最新版以及修复
fix by #354
