### ISSUE TITLE
查询不了持仓

### ISSUE THREAD

**Issue by huangguanliu** [shidenggui/easytrader#357]
## env

OS: windows server2008 R2
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.18.6
BROKER_TYPE: 通用同花顺

## problem
新版同花顺已经不能通过拷贝查询持仓，所以用了这个
user.grid_strategy = grid_strategies.Xls

执行user.position后，报错：
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\2\\tmpuhcj_6mr.csv'
同花顺也会提示找不到路径。

**Comment by zgpnuaa** [comment]
我也遇到了同样的问题，请问你解决了吗？ @huangguanliu

**Comment by zgpnuaa** [comment]
看样子是保存xls文件时路径有问题，我是Win10系统，不知道是不是Win10系统的原因 @huangguanliu

**Comment by huangguanliu** [comment]
> 看样子是保存xls文件时路径有问题，我是Win10系统，不知道是不是Win10系统的原因 @huangguanliu

修改一下easytrader文件夹下面的grid_trategies.py,170多行的那个get函数里:
temp_path = tempfile.mktemp(suffix=".csv")
改成
temp_path = tempfile.mktemp(suffix=".csv",dir=r"自行制定的路径")

**Comment by zgpnuaa** [comment]
谢谢，终于解决了 @huangguanliu

**Comment by huangguanliu** [comment]
> 谢谢，终于解决了 @huangguanliu

哈哈，祝股市长红

**Comment by zgpnuaa** [comment]
> > 谢谢，终于解决了 @huangguanliu
> 
> 哈哈，祝股市长红

哈哈，祝股票长红 @huangguanliu
