### ISSUE TITLE
银河查询当前持仓时候，买入冻结数为0

### ISSUE THREAD

**Issue by indigo200** [shidenggui/easytrader#36]
反复测试了几天，情况都是如此

**Comment by shidenggui** [comment]
希望能把具体的信息贴上

**Comment by indigo200** [comment]
[[{'证券名称': '健康分级'}, {'证券代码': '164401'}, {'当前持仓': '600'}, {'股份余额': '600'}, {'股份可用': '0'}, {'参考市值': '587.40'}, {'参考市价': '0.979'}, {'参考盈亏': "<span style='color:#ff3232;'>10.80</span>"}, {'盈亏比例(%)': "<span style='color:#ff3232;'>1.87%</span>"}, {'买入冻结': '0'}, {'卖出冻结': '600'}
, {'股东代码': 'xxxxx'}, {'交易市场': '深A'}], [{'证券名称': '军工分级'}, {'证券代码': '502003'}, {'当前持仓': '720000'}, {'股份余额': '720000'}, {'股份可用': '0'}, {'参考市值': '795600.00'}, {'参考市价': '1.105'}, {'参考盈亏': "<span
 style='color:#ff3232;'>120716.16</span>"}, {'盈亏比例(%)': "<span style='color:#ff3232;'>17.93%</span>"}, {'买入冻结': '0'}, {'卖出冻结': '0'}, {'股东代码': 'yyyy'}, {'交易市场': '沪A'}], [{'证券名称': '50分级'}, {'证券代码': '502048'}, {'当前持仓': '200'}, {'股份余额': '0'}, {'股份可用': '0'}, {'参考市值': '211
.60'}, {'参考市价': '1.058'}, {'参考盈亏': "<span style='color:#00e600;'>-0.10</span>"}, {'盈亏比例(%)': "<span style='color:#00e600;'>-0.09%</span>"}, {'买入冻
结': '0'}, {'卖出冻结': '0'}, {'股东代码': 'yyyy'}, {'交易市场': '沪A'}],[{'证券名称': '医疗分级'}, {'证券代码': '502056'}, {'当前持仓': '300'}, {'股份余
额': '300'}, {'股份可用': '300'}, {'参考市值': '328.50'}, {'参考市价': '1.095'}, {'参考盈亏': "<span style='color:#ff3232;'>326.49</span>"}, {'盈亏比例(%)': "<s
pan style='color:#ff3232;'>15542.86%</span>"}, {'买入冻结': '0'}, {'卖出冻结': '0'}, {'股东代码': 'yyyy'}, {'交易市场': '沪A'}]]

 像我今天测试的502048，显示当前持仓是对的(200股)，但买入冻结就为0

**Comment by shidenggui** [comment]
我观察银河官方的返回就是 0 吧？你可以直接上 web 客户端看下冻结数会不会变

**Comment by shidenggui** [comment]
银河官方返回为零
