### ISSUE TITLE
DEBUG 模式未生效

### ISSUE THREAD

**Issue by pronyl** [shidenggui/easytrader#361]
easytrader.use('htzq_client', debug=False) 
关不掉DEBUG

## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

**Comment by qmzhn** [comment]
把这个装饰器取消掉@perf_clock
