### ISSUE TITLE
当前雪球组合交易是否已停止维护？

### ISSUE THREAD

**Issue by melissa135** [shidenggui/easytrader#363]
## env

OS: linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: latest
BROKER_TYPE:  xq 

## problem
[ERROR] xqtrader.py 387: 调仓错误: 组合服务器出错

**Comment by shidenggui** [comment]
是的，这个模块本身是由另外一个开发者开发的。他停止后，模块就处于放任状态。
