### ISSUE TITLE
五档行情功能

### ISSUE THREAD

**Issue by reynold0510** [shidenggui/easytrader#366]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
非常感谢作者提供的API。 可以建议将来有机会加上从交易委托系统中提取五档行情的功能吗？因为其他免费行情提供方的行情并不适合作为买入和卖出价格，也不能支持大量实时的数据访问（比如整个开盘时间内每秒钟访问一次）。建议仅供参考，再次多谢作者的付出。非常好的API。

**Comment by shidenggui** [comment]
多谢建议，不过暂时没有计划。
