### ISSUE TITLE
refresh建议用F5按键

### ISSUE THREAD

**Issue by xayjin** [shidenggui/easytrader#369]
## env

OS: win7
PYTHON_VERSION: 3.8
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
ClientTrader的refresh有的版本同花顺无效。
建议：可以直接用pywinauto模拟键盘F5来刷新，比切换买入界面更直接有效。

**Comment by qmzhn** [comment]
兄弟，你的提议非常好！

**Comment by shidenggui** [comment]
close by 57a58e22d453f239348b6f15c40aac47d5f918b0
