### ISSUE TITLE
华泰证券，出现程序停止响应，然后就一直hang在那儿

### ISSUE THREAD

**Issue by auspix** [shidenggui/easytrader#374]
## env

OS: win7
PYTHON_VERSION: 3.8
EASYTRADER_VERSION: 0.20.1
BROKER_TYPE: ht

## problem
先后调用prepare, balance, position, 调用position的时候有时候会出现程序停止响应的提示，然后easytrader会一直停在那儿没有反应。

## how to repeat
先后调用prepare, balance, position

![image](https://user-images.githubusercontent.com/20781994/82262286-32381580-9993-11ea-97bc-7ca2802742f6.png)

**Comment by shidenggui** [comment]
本地无法复现。
