### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by zhlzhl123** [shidenggui/easytrader#379]
OS: win10
PYTHON_VERSION: 3.8

C:\Users\zhlzh>pip install easytrader
Collecting easytrader
  Using cached easytrader-0.20.4.tar.gz (35 kB)
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting rqopen-client
  Using cached rqopen-client-0.0.6.tar.gz (4.7 kB)
    ERROR: Command errored out with exit status 1:
     command: 'd:\software\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\zhlzh\\AppData\\Local\\Temp\\pip-install-8n_tyhxw\\rqopen-client\\setup.py'"'"'; __file__='"'"'C:\\Users\\zhlzh\\AppData\\Local\\Temp\\pip-install-8n_tyhxw\\rqopen-client\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\zhlzh\AppData\Local\Temp\pip-pip-egg-info-xsnnfm9r'
         cwd: C:\Users\zhlzh\AppData\Local\Temp\pip-install-8n_tyhxw\rqopen-client\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\zhlzh\AppData\Local\Temp\pip-install-8n_tyhxw\rqopen-client\setup.py", line 24, in <module>
        install_requires=[
      File "C:\Users\zhlzh\AppData\Local\Temp\pip-install-8n_tyhxw\rqopen-client\setup.py", line 25, in <listcomp>
        str(ir.req)
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

安装到rqopen-client时出错？虽然貌似rqopen-client九天前已经从requirements.txt里删掉了，请问该怎么解决呢？

**Comment by shidenggui** [comment]
fix by b37661b
