### ISSUE TITLE
不同券商返回值 字段名称统一下

### ISSUE THREAD

**Issue by whcobra** [shidenggui/easytrader#38]
namemap={'参考市值':'market_value'
                ,'可用资金':'enable_balance'
                ,'总资产':'asset_balance'
                ,'资金余额':'current_balance'
                ,'币种':'money_type'
                ,'证券名称':'stock_name'
                ,'证券代码':'stock_code'
                ,'股份可用':'enable_amount'
                ,'当前持仓':'current_amount'
                ,'参考市价':'last_price'
                ,'参考盈亏':'income_balance'
                ,'委托时间':'report_time'
                ,'状态说明':'entrust_status'
                ,'委托序号':'entrust_no'
                }
类似这样
这样以后不同的券商返回的字段就可以统一了
如果不同的券商，前端调用就比较方便了，

**Comment by shidenggui** [comment]
曾经考虑过，如果不同券商的同个名字有不同的意义就麻烦了

**Comment by oldwain** [comment]
原来有人提过这个问题了。
还是应该统一。
至于不同券商的同个名字有不同的意义， 这个在各个接口的实现中调整好就行， easytrader的使用者那里是统一的。

**Comment by shidenggui** [comment]
暂时不考虑这样做
