### ISSUE TITLE
install easytrader fail

### ISSUE THREAD

**Issue by withtea** [shidenggui/easytrader#380]
## env

OS: win10
PYTHON_VERSION: 3.8.1
EASYTRADER_VERSION: lastest version
BROKER_TYPE: error

## problem
D:\easytrader>pip install easytrader
Collecting easytrader
  Using cached easytrader-0.20.4.tar.gz (35 kB)
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting rqopen-client
  Using cached rqopen-client-0.0.6.tar.gz (4.7 kB)
    **ERROR: Command errored out with exit status 1:
     command: 'd:\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-18hnelkp\\rqopen-client\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-18hnelkp\\rqopen-client\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Administrator\AppData\Local\Temp\pip-pip-egg-info-ud9g7q5i'
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-18hnelkp\rqopen-client\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-18hnelkp\rqopen-client\setup.py", line 24, in <module>
        install_requires=[
      File "C:\Users\Administrator\AppData\Local\Temp\pip-install-18hnelkp\rqopen-client\setup.py", line 25, in <listcomp>
        str(ir.req)
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.**

## how to repeat
pip install easytrader will be repeated

**Comment by zhlzhl123** [comment]
#379 
和你同一个问题

**Comment by shidenggui** [comment]
fix by b37661bee2ce79f21430eef2c424778059c7b19c
