### ISSUE TITLE
无法撤单

### ISSUE THREAD

**Issue by wsxwd** [shidenggui/easytrader#467]
## env

OS: win10
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.23.0
BROKER_TYPE: yh

## problem
无法撤单。代码中撤单函数通过获取委托记录的坐标，然后双击实现撤单。CANCEL_ENTRUST_GRID_ROW_HEIGHT这个参数是否和分辨率相关，是否有更好的实现方式？

**Comment by oloopy** [comment]
国金证券也无法撤单，错误提示
pywinauto.findwindows.ElementNotFoundError: {'control_id': 2406, 'class_name': 'Static', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '网上股票交易系统5.0', Afx:400000:b:10003:6:300839, 264502>, 'backend': 'win32'}
