### ISSUE TITLE
关于Redhat下的运行

### ISSUE THREAD

**Issue by indigo200** [shidenggui/easytrader#48]
我用vmware装的Redhat 5.2调试，发现即使强制easytrader.use('yh',debug=True)，也不可以使调试信息出来。也不知道保持在线是否正确。可否确认该现象是否正常，谢谢

**Comment by shidenggui** [comment]
其他券商有信息吗？保持在线的线程目前是没有打 log 的

**Comment by indigo200** [comment]
Windows下面是有log的。。如果没有log，有什么办法可以确认当前在线呢？

**Comment by shidenggui** [comment]
有些券商加了重新登录的机制，有些没
