### ISSUE TITLE
银河股东内容列表超出2行后会出现一些问题, 导致无法登陆与下单

### ISSUE THREAD

**Issue by chenfeng432** [shidenggui/easytrader#51]
我的账户, 股东列表页面, 内容有3行, 最底一行最后一列内容为设为主股东, 这样为导致登陆失败, 也不能下单

在 yhtrader.py 文件的第300行.
我修改为:

            data = data.replace('\r','').replace('\n','').replace('\t','').replace('&nbsp;','')
            search_result_content = re.findall(r'<td nowrap=\"nowrap\">(.*?)</td>', data)

**Comment by shidenggui** [comment]
主要是我没有遇到这个情况，不知道3行的返回到底是怎么样的，不太好改
