### ISSUE TITLE
雪球怎么登录呢？

### ISSUE THREAD

**Issue by viponedream** [shidenggui/easytrader#55]
抓包不到密码的地方啊。
    user = easytrader.use('xq')
    user.prepare('xq.json')

提示该邮箱尚未注册

**Comment by shidenggui** [comment]
雪球不需要抓包密码

**Comment by viponedream** [comment]
我网页可以用手机号登录的。

**Comment by shidenggui** [comment]
雪球直接用明文密码就可以了，不需要抓取 post
