### ISSUE TITLE
华泰没有较好的确认成交的方法

### ISSUE THREAD

**Issue by hahahay** [shidenggui/easytrader#59]
对于华泰，买卖单成交后：
1、成交的委托会从entrust中删除，entrust中始终只有“未报”、“已报”、 “废单”，没有“已成”
2、在交易时段内user.get_exchangebill('开始日期', '截止日期') 查不到当天已经成交了的买卖单
目前看起来只能通过position的current_amount变化的方式确认成交。

而对于佣金宝，买卖单成交后：
1、成交后在entrust有记录，显示为“已成”
2、user.current_deal有显示刚刚的成交
所以佣金宝用于确认委托成交的方法较方便。

**不知是否能添加华泰可用的，更便捷的委托单成交确认方式？**

**Comment by shidenggui** [comment]
这个需要看有没有对应的 `http` 接口，因为我目前没有在用华泰了，所以要看有没有人贡献对应的接口

**Comment by zjw0358** [comment]
我弄了一个查询当天交易记录的，如何提交代码上来？

**Comment by shidenggui** [comment]
你先 fork 我的 repo，然后修改后提交到你自己的分支上，然后发 pull request 给我请求合并
