### ISSUE TITLE
雪球组合不是实盘，代码问题多多

### ISSUE THREAD

**Issue by xdbaqiao** [shidenggui/easytrader#76]
雪球组合是比例调仓，按仓位管理，实时成交，基本跟price和amount无关。也就是说接口暴露出weight足矣，price和amount都没用，代码里面weight 是计算来的，还round四舍五入，太容易导致仓位不足，出错，建议考虑修改一下。

**Comment by haogefeifei** [comment]
可以考虑在buy sell方法里面加一个weight参数就可搞定问题。。  当初这样做是为了能和实盘无缝切换。。 只不过最终没有做到。。。

**Comment by xdbaqiao** [comment]
雪球实盘和组合比较难无缝切换吧，毕竟两种不同的业务逻辑。可否独立出来，分为两部分？
