### ISSUE TITLE
银河证券password为动态密码，无法登陆

### ISSUE THREAD

**Issue by fayeshine** [shidenggui/easytrader#79]
在官方上，每次登陆都都会在POST抓到不同的动态密码，因此通过easytrader无法连接，总是报密码不对的错。
另外，readme里的需要看hardinfo是什么意思？怎么使用hardinfo？

**Comment by shidenggui** [comment]
* 银河不同的动态密码随便取一个都可以用
* hardinfo 是初始版本的残留，现在已经不需要了。我已经更新了说明文件

**Comment by fayeshine** [comment]
@shidenggui ,随便抓的一个，好像不能用，提示密码错误。话说这个是要同一台机器么？我在windows上机器抓的一个密码，在另一台linux能用么

**Comment by shidenggui** [comment]
并不需要同一台机器。银河我问了下其他人是正常使用的的

**Comment by fayeshine** [comment]
@shidenggui ,你看easytrader二群的里人讨论的，我们几个试了都失败了

**Comment by fayeshine** [comment]
@shidenggui 尝试成功了，原来要网页登陆时，保持连接，然后使用动态密码登陆，这样就可以连上了。如果网页断开了，再用这个动态密码以后就会失败。

**Comment by shidenggui** [comment]
那估计是银河改了策略，我两个月前还是正常使用的

**Comment by fayeshine** [comment]
我的意思是第一次用动态密码时，需要网页同时登陆，之后就成功了，不需要网页登陆了，可能需要在readme里加个注释说明一下

**Comment by Emptyset110** [comment]
@fayeshine 我刚才更新了一下密文密码。不过我网页登出，云端easytrader也退出重新登录依旧可以登录啊。。。你确定换成了动态密码么？

**Comment by Emptyset110** [comment]
@fayeshine 虽然确实是动态密码，不过好像原来的密码也能用……不知道什么情况，不清楚什么时候会失效……

**Comment by Emptyset110** [comment]
如果是这样的话，是不是可以多抓几次动态密码，存成一个池子，万一哪个动态密码失效了，程序自动随机切换一个。

**Comment by Emptyset110** [comment]
如果是这样的话，是不是可以多抓几次动态密码，存成一个池子，万一哪个动态密码失效了，程序自动随机切换一个。

**Comment by laowalter** [comment]
建议增加 人工干预的接口，佣金宝也经常出现无法正确识别验证码的情况。

**Comment by batnlee** [comment]
似乎隔一段时间，之前的动态密码就会失效

**Comment by fayeshine** [comment]
@batnlee 隔多久会失效？

**Comment by batnlee** [comment]
@fayeshine 不确定，不过前两个月开始用的，今天就不行了，只好重新取一个

**Comment by shidenggui** [comment]
暂时移除了yh的支持
