### ISSUE TITLE
连雪球进行交易的问题

### ISSUE THREAD

**Issue by yyb229** [shidenggui/easytrader#88]
------------
  File "xqtrader.py", line 299, in __trade
    stock = self.__search_stock_info(stock_code)

{   'code': u'600132',
    'data': {   'code': '600132',
                'key': '47bce5c74f',
                'market': 'cn',
                'size': '300'},
    'r': ,
    'self': ,
    'stocks': {   u'error_code': u'400016',
                  u'error_description': u'\u9047\u5230\u9519\u8bef\uff0c\u8bf7\u5237\u65b0\u9875\u9762\u6216\u8005\u91cd\u65b0\u767b\u5f55\u5e10\u53f7\u540e\u518d\u8bd5',
                  u'error_uri': u'/stock/p/search.json'}}
------------
你好，shidenggui，我在使用easytrader的时候，登录雪球后，查看组合的资金状况和持仓状况都没有问题，但是调用查看今日委托单接口，买、卖接口的时候都会报错。上面是买接口所报的错，对应的中文错误信息是：遇到错误，请刷新页面或者重新登录帐号后再试
我想知道是否是cookie有问题，我要怎么才能解决这个问题？

**Comment by shidenggui** [comment]
@haogefeifei

**Comment by shidenggui** [comment]
重构了下雪球，你可以看看还有没有问题
