### ISSUE TITLE
请解决雪球账户股票买卖数量有限问题

### ISSUE THREAD

**Issue by fdsh99** [shidenggui/easytrader#97]
easytrader用于雪球模拟若股票数量超过15、16只样子，就会出现错误。如目前我的雪球账户中大概有18只股票，买卖都不再能执行了，必须手工先卖出几只股票后，才能用easytrader操作。买入也是如此，当一个空账户，最多能买入15-6只股票，后面的就不行了。请帮助解决。谢谢！

**Comment by shidenggui** [comment]
@haogefeifei

**Comment by fdsh99** [comment]
经过测试，只要POST以下数据项就足够了，这样可有效提高雪球账户中股票处理数量。
            positions.append({
                "stock_name": pos['stock_name'],
                "stock_id":pos['stock_id'],
                "segment_name":pos['segment_name'],
                "weight":pos['weight'],
                "proactive":pos['proactive']
                })

**Comment by shidenggui** [comment]
这样不会有影响吗？理论下雪球对post的数据应该没有限制才是

**Comment by haogefeifei** [comment]
买入报什么错误？

**Comment by haogefeifei** [comment]
话说雪球组合最多也就允许20支

**Comment by shidenggui** [comment]
用这个方法能突破雪球20只股票的限制吗
