### ISSUE TITLE
关于长期保持登录状态的问题

### ISSUE THREAD

**Issue by fjfzzl** [shidenggui/easytrader#98]
我想问一下，我在执行user = easytrader.use('yjb') 和 user.prepare('yjb.json') ，登录之后，多长时间不操作，session会失效，能否在你的程序中，直接加入维持登陆状态的功能。因为有时候策略需要运行几个月时间，万一被服务器踢出了，程序执行就会出现不可预见的错误，这个很麻烦。

盼回复！

**Comment by shidenggui** [comment]
目前已经有心跳线程 10 s 发送一次心跳。但是有时候还是会掉线

**Comment by fjfzzl** [comment]
那能否加一个函数功能，用来判断是否在登录状态，这样子在策略运行过程中，先判断是否在登录状态，如果是，直接下单，如果不是，再重新登录，然后下单。这样可否？

**Comment by shidenggui** [comment]
这个已经有了，你可以直接看源码
