### ISSUE TITLE
不能交易etf?

### ISSUE THREAD

**Issue by lyghid** [shidenggui/easytrader#99]
user.buy(510050, price=2.278, amount=3600)
user.buy(150019, price=0.885, amount=6300)
同时发出买入指令，510050没有委托记录，其他都能成交。试了一下其他510开头的etf都没有委托记录。

**Comment by shidenggui** [comment]
可能是沪深判断有误，你直接带上 'shxxxxxx' 或者 'szxxxxx' 试试

**Comment by lyghid** [comment]
user.buy(sh510050, price=2.100, amount=100)
Traceback (most recent call last):

  File "<ipython-input-24-7dac3391e0cb>", line 1, in <module>
    user.buy(sh510050, price=2.100, amount=100)

NameError: name 'sh510050' is not defined

加上“”sh“”还是有问题
